### ISSUE TITLE
Version 0.2.1 not published to marketplace

### ISSUE THREAD

**Issue by vandamm** [aidmax/structurizr-cli-action#11]
While the repository includes v0.2.1 release, marketplace page states v0.2.0 as latest one, and it's non-functional.
<img width="445" alt="Screenshot 2022-04-26 at 12 36 50" src="https://user-images.githubusercontent.com/576786/165270650-3869648a-4f3f-49c5-ad63-07a558e97d88.png">
<img width="512" alt="Screenshot 2022-04-26 at 12 36 39" src="https://user-images.githubusercontent.com/576786/165270617-03595611-52f8-45ff-8694-67cb1bbae534.png">

**Comment by aidmax** [comment]
Thanks @vandamm for bringing that up. 
I have fixed it.
