### ISSUE TITLE
Unrecognized option: -docs

### ISSUE THREAD

**Issue by mattkoch614** [aidmax/structurizr-cli-action#9]
I am getting an `Unrecognized option: -docs` error when my workflow tries to run:

https://github.com/NYPL/c4-diagrams-DXP/blob/main/.github/workflows/structurizr-cli.yml

**Comment by aidmax** [comment]
Hi @mattkoch614  fixed in https://github.com/aidmax/structurizr-cli-action/releases/tag/v0.2.1

Please check it out.

**Comment by mattkoch614** [comment]
@aidmax  Fantastic, this solved it! Thanks!
